docs: Update Showcase Dynamic plugins documentation to remove the part related to the old backend system
janus-idp/backstage-showcase pull request #1105
Opened 2024-03-21 19:14 UTC by jesuino

Fix for [RHIDP-1325](https://issues.redhat.com/browse/RHIDP-1325)

2024-04-02 18:30 UTC, schultzp2020 approved these changes
/approve
/lgtm

2024-04-02 21:15 UTC, davidfestal requested changes

2024-04-02 21:15 UTC, davidfestal commented on showcase-docs/dynamic-plugins.md
> +    "@janus-idp/cli": "^1.7.5"
```suggestion
    "@janus-idp/cli": "^1.7.7"
```

2024-04-02 21:15 UTC, davidfestal commented on showcase-docs/dynamic-plugins.md
> +To be compatible with the showcase dynamic plugin support, and used as dynamic plugins, existing plugins must be completed code-wise, as well as rebuilt with a dedicated CLI command.
```suggestion
To be compatible with the showcase dynamic plugin support, and used as dynamic plugins, existing plugins must be based on, or compatible with, the new backend system, as well as rebuilt with a dedicated CLI command.
```

2024-04-02 21:15 UTC, davidfestal commented on showcase-docs/dynamic-plugins.md
> +    "@backstage/backend-dynamic-feature-service": "0.2.3",
In fact that should not even be necessary in most cases, when using a plugin made for the new backend system.

2024-04-02 21:15 UTC, davidfestal commented on showcase-docs/dynamic-plugins.md
> +    "@backstage/backend-dynamic-feature-service": "0.2.3",
So line https://github.com/janus-idp/backstage-showcase/pull/1105/files#diff-8d2e5712d5ef532a983602f4c771597e41d8c082d7801f59f6003fe9f66e2a89L28 can be removed.

Line https://github.com/janus-idp/backstage-showcase/pull/1105/files#diff-8d2e5712d5ef532a983602f4c771597e41d8c082d7801f59f6003fe9f66e2a89R28 should also be removed

2024-04-02 21:15 UTC, davidfestal commented on showcase-docs/dynamic-plugins.md
> +    "@backstage/backend-dynamic-feature-service": "0.2.3",
In line 38 you should use:

```
          "export-dynamic": "janus-cli package export-dynamic-plugin ----embed-as-dependencies"
```

2024-04-02 21:15 UTC, davidfestal commented on showcase-docs/dynamic-plugins.md
>    "files": [
This required change can be removed now

2024-04-02 21:15 UTC, davidfestal commented on showcase-docs/dynamic-plugins.md
> +#### Creating entry points
```suggestion
#### Required entry points
```

2024-04-02 21:15 UTC, davidfestal commented on showcase-docs/dynamic-plugins.md
> +It is required to create entry points (using `createBackendPlugin` or `createBackendModule`) to enable a backend plugin's dynamic functionality.
```suggestion
The new backend system standard entrypoint (created using  `createBackendPlugin()` or `createBackendModule()`) should be exported as the default export of either the main package or of an `alpha` package (if the new backend support is still provided as `apha` APIs).

So this doesn't add any additional requirement on top of the standard plugin development guidelines of the new backend system.
```

2024-04-03 19:13 UTC, jesuino commented
Thanks for the review @davidfesta l I made the requested changes.

2024-04-04 23:07 UTC, jesuino commented on showcase-docs/dynamic-plugins.md
> +    "export-dynamic": "janus-cli package export-dynamic-plugin ----embed-as-dependencies"
done, thanks!

2024-04-05 07:32 UTC, davidfestal approved these changes

2024-04-08 13:57 UTC, davidfestal commented
/lgtm

2024-04-08 15:59 UTC, davidfestal commented
/lgtm

2024-04-08 16:09 UTC, merged