Add a new tab to the EntityPage for the Quarkus console
janus-idp/backstage-showcase pull request #1154
Opened 2024-04-03 08:15 UTC by cmoulliard

## Description

This PR:
- Add a new tab to the `./packages/app/src/components/catalog/EntityPage/index.tsx` file in order to allow to display the [Quarkus console](https://github.com/q-shift/backstage-plugins)
- Enhance the documentation page to better explain how to run locally the dynamic plugins with `yarn start`
- Add a Table of Contents to the dynamic-plugins.md file

## Which issue(s) does this PR fix

- Fixes #1147 

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [x] Documentation is updated if necessary (requirement for new features)
- [x] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2024-04-03 09:10 UTC, davidfestal requested changes
2 remarks here:
- Do you think you could create a dedicated PR for the Docs enhancement ?
- With dynamic plugins, we should not require changing the source code of the frontend application in order to wire a dynamic plugin. That seems like an anti-pattern. **_Users of the showcase that will want to bring their own plugins in a dedicated tab will not be able to change the showcase image_** . @tumido @gashcrumb Any idea about how to contribute a new tab ? I assume we should have something, right ?

2024-04-03 09:16 UTC, davidfestal commented
> @tumido @gashcrumb Any idea about how to contribute a new tab ? I assume we should have something, right ?

And if not the it seems to me it would be quite urgent to provide an option.

2024-04-03 09:17 UTC, cmoulliard commented
> * That seems like an anti-pattern.

I fully agree with you but my PR has been created based on discussions with @gashcrumb as currenly this is the only way to add a tab

2024-04-03 09:18 UTC, cmoulliard commented
> * Do you think you could create a dedicated PR for the Docs enhancement ?

I can do that but then it will be needed to remove commits pushed on this PR ....

2024-04-03 09:23 UTC, davidfestal commented
> I can do that but then it will be needed to remove commits pushed on this PR ....

I assume this PR should be rebased yes, or possibly replaced b the new one.

BTW I don't really see the point in adding a TOC, since one is already constructed automatically by GH (as would be in other markdown viewers) based on the Markown structure:

![Screenshot from 2024-04-03 11-22-04](https://github.com/janus-idp/backstage-showcase/assets/686586/8a2ad1c9-b409-40da-a12c-0bdf7b8d0be5)

2024-04-03 09:24 UTC, davidfestal commented
> > The image is available at: `quay.io/janus-idp/backstage-showcase:pr-1154`!
> 
> I did a test on our cluster using the image of the PR and that works too.

My main problem is that it seems to me that **_we should not need to create a new container image_** in order to add a tab specific to a dynamic plugin.

2024-04-03 09:28 UTC, cmoulliard commented
> BTW I don't really see the point in adding a TOC, since one is already constructed automatically by GH (as would be in other markdown viewers) based on the Markown structure:

I removed the TOC from this PR

2024-04-03 09:29 UTC, tumido commented
So... The code is completely correct and valid.

Secondly, you should really think twice before adding new tabs. The fact that you can't just add a new tab by the dynamic plugins mechanism is 100% intentional. Our aim was to always reduce the amount of tabs we provide. We don't want to end up in a situation where we have a new tab per plugin.

Each tab should represent a purpose that is generic and common to every entity of the same kind and type in the catalog. That's why we don't have a distinct GitHub Actions tab and Tekton tab -> we have a single CI tab instead.

The presence of a new tab should be a PM/UX question, this is not something we should decide only on code quality/review basis.

2024-04-03 09:32 UTC, cmoulliard commented
> Each tab should represent a purpose that is generic and common to every entity of the same kind and type in the catalog. That's why we don't have a distinct GitHub Actions tab and Tekton tab -> we have a single CI tab instead.
> 
> The presence of a new tab should be a PM/UX question, this is not something we should decide only on code quality/review basis.

I agree with you and that will discussed soon between the Quarkus's Product Manager and RHDH team.

**FYI**: The Quarkus Console plugin could become (if needed) a runtime plguin supporting: Quarkus, Spring Boot, EAP, etc java runtimes

2024-04-03 09:35 UTC, davidfestal commented
> The fact that you can't just add a new tab by the dynamic plugins mechanism is 100% intentional

I think that even this assertion should be validated by PM / UX.
It might be that the availability of such an option (to place a dynamic plugin in a new tab) would still be required, even though not the default or the recommended way.

cc @christophe-f

2024-04-04 02:29 UTC, christophe-f commented
Like Tom mentioned, I agree that we should not ship too many tabs by default. 
With that said, a user should be able to create, remove, rename tabs as they wish and not be limited. We should definitely provide this feature.

We've been focusing a lot on the Component kind where most of the tabs are already present, but if someone would like to add more tab to the user, groups or custom Kind, currently they are not allowed.

2024-04-04 19:57 UTC, davidfestal commented
Issue https://github.com/janus-idp/backstage-showcase/issues/1160 was opened for this purpose,to avoid fixing this with a plugin-specific fix.

2024-06-13 14:30 UTC, invincibleJai commented
> Issue #1160 was opened for this purpose,to avoid fixing this with a plugin-specific fix.

@cmoulliard I see https://github.com/janus-idp/backstage-showcase/pull/1173 is merged and the associated issue is closed

so do we still need this PR or it can be closed?

cc @gashcrumb

2024-06-13 15:00 UTC, gashcrumb commented
Yep, this approach shouldn't be necessary anymore, so let's close this.

2024-06-13 15:00 UTC, closed without merging