RHIDP-1478: Include HTTP Request as pre-loaded Plugin to RHDH
janus-idp/backstage-showcase pull request #1207
Opened 2024-04-24 20:49 UTC by jesuino

## Description

RHIDP-1478: Include HTTP Request as pre-loaded Plugin to RHDH

Adding a wrapper to the plugin roadiehq/scaffolder-backend-module-http-request.

## Which issue(s) does this PR fix

https://issues.redhat.com/projects/RHIDP/issues/RHIDP-1478

- Fixes RHIDP-1478?

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2024-04-25 08:33 UTC, davidfestal requested changes

2024-04-25 08:33 UTC, davidfestal commented on dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/package.json
> +    "@backstage/backend-dynamic-feature-service": "^0.2.2",
I don't think you need this dependency.

2024-04-25 08:33 UTC, davidfestal commented on dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/package.json
> +    "@backstage/cli": "0.25.2",
This should be the same dependency as for other wrappers

2024-04-25 08:33 UTC, davidfestal commented on dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/package.json
> +    "@backstage/cli": "0.25.2",
Same for the ` @janus-idp/cli` dependency.

2024-04-25 08:33 UTC, davidfestal commented on dynamic-plugins/wrappers/roadiehq-scaffolder-backend-module-http-request/package.json
> +    "@backstage/backend-plugin-api": "0.6.13",
Wouldn't it be possible to use on of the dependency versions already present in the `yarn.lock`: https://github.com/janus-idp/backstage-showcase/pull/1207/files#diff-51e4f558fae534656963876761c95b83b6ef5da5103c4adef6768219ed76c2deR2481 ?

2024-04-25 18:04 UTC, jesuino commented
Hello @davidfestal  - thanks for your comments, I made the requested changes. Please let me know if I am missing something.

Thanks!

2024-04-25 22:02 UTC, davidfestal approved these changes

2024-04-25 22:28 UTC, merged

2024-04-29 09:11 UTC, davidfestal commented
cc @gashcrumb