Fixed broken links to plugins in main README.md file
janus-idp/backstage-showcase pull request #1308
Opened 2024-06-06 16:06 UTC by 04kash

## Description

Fixed broken links to plugins in main README.md file for the following:
- GitHub Pull Requests plugin
- GitHub Actions plugin
- GitHub Issues plugin
- Azure DevOps plugin
- Jenkins plugin
- PagerDuty
- Lighthouse plugin
- Dynatrace plugin

## Which issue(s) does this PR fix

- Fixes #1304 

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2024-06-06 16:47 UTC, gashcrumb commented
/ok-to-test

2024-06-06 16:48 UTC, gashcrumb approved these changes
:+1:

2024-06-06 17:50 UTC, Zaperex requested changes
Can we link to the plugin instead of to the workspace the plugins are located in?

2024-06-06 17:50 UTC, Zaperex commented on README.md
> +- [Jenkins plugin](https://github.com/backstage/community-plugins/tree/main/workspaces/jenkins)
```suggestion
- [Azure DevOps plugin](https://github.com/backstage/community-plugins/tree/main/workspaces/azure-devops/plugins/azure-devops/README.md)
- [Jenkins plugin](https://github.com/backstage/community-plugins/tree/main/workspaces/jenkins/plugins/jenkins/README.md)
```

2024-06-06 17:50 UTC, Zaperex commented on README.md
> +- [GitHub Issues plugin](https://github.com/backstage/community-plugins/tree/main/workspaces/github-issues)
```suggestion
- [GitHub Pull Requests plugin](https://github.com/backstage/community-plugins/tree/main/workspaces/github-pull-requests-board/plugins/github-pull-requests-board/README.md)
- [GitHub Actions plugin](https://github.com/backstage/community-plugins/tree/main/workspaces/github-actions/plugins/github-actions/README.md)
- [GitHub Issues plugin](https://github.com/backstage/community-plugins/tree/main/workspaces/github-issues/plugins/github-issues/README.md)
```

2024-06-06 17:50 UTC, Zaperex commented on README.md
> +- [Dynatrace plugin](https://github.com/backstage/community-plugins/tree/main/workspaces/dynatrace)
```suggestion
- [Lighthouse plugin](https://github.com/backstage/community-plugins/tree/main/workspaces/lighthouse/plugins/lighthouse/README.md)
- [Dynatrace plugin](https://github.com/backstage/community-plugins/tree/main/workspaces/dynatrace/plugins/dynatrace/README.md)
```

2024-06-06 20:10 UTC, Zaperex commented
/ok-to-test

2024-06-06 20:10 UTC, Zaperex approved these changes
/lgtm

2024-06-10 13:09 UTC, Zaperex approved these changes
/lgtm

2024-06-10 13:13 UTC, merged