chore: add RHDH scripts and add them as techdocs
janus-idp/backstage-showcase pull request #1486
Opened 2024-08-14 20:10 UTC by Zaperex

## Description

Adding the `patch-package` and RHDH setup scripts along with their documentation.
Update the techdocs configurations to use showcase docs rather than the mock docs.

## Which issue(s) does this PR fix

- Fixes #?

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [x] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2024-08-14 20:11 UTC, Zaperex commented
It seems the RHDH theme is making the header sizes way too small: 
![image](https://github.com/user-attachments/assets/1865153e-ccde-484b-81ad-d264fb86df3a)

2024-10-08 16:08 UTC, nickboldt requested changes
Note that https://github.com/janus-idp/backstage-showcase/tree/release-1.3/showcase-docs have moved to https://github.com/janus-idp/backstage-showcase/tree/main/docs so some refactoring should be done on this PR

2024-10-09 20:03 UTC, nickboldt commented
Looks good but we might want to address some of those sonarcloud issues. https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&pullRequest=1486&types=VULNERABILITY&severities=BLOCKER%2CCRITICAL%2CMAJOR%2CMINOR&inNewCodePeriod=true&sinceLeakPeriod=true&id=janus-idp_backstage-showcase

@kim-tsao WDYT?

2024-10-10 18:36 UTC, nickboldt approved these changes

2024-10-10 18:36 UTC, merged