[Test Automation] Verify RBAC plugin - REST API
janus-idp/backstage-showcase pull request #1488
Opened 2024-08-15 01:45 UTC by Omar-AlJaljuli

## Description

Test Automation that verifies all aspects of the RBAC REST API endpoints work.

## Which issue(s) does this PR fix

https://issues.redhat.com/browse/RHIDP-743

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2024-08-15 13:55 UTC, Omar-AlJaljuli commented
/retest

2024-08-15 18:59 UTC, Omar-AlJaljuli commented
/retest

2024-08-15 19:51 UTC, Omar-AlJaljuli commented
/retest

2024-08-16 13:39 UTC, josephca commented
Hi @Omar-AlJaljuli, is this ready to be reviewed? I assume it's waiting to get e2e tests passed, right? FYI, I just updated the branch to rebase.

2024-08-16 13:56 UTC, Omar-AlJaljuli commented
> Hi @Omar-AlJaljuli, is this ready to be reviewed? I assume it's waiting to get e2e tests passed, right? FYI, I just updated the branch to rebase.

Yes it is. It was just failing both e2e tests yesterday, but hopefully they pass after the rebase.

2024-08-19 23:15 UTC, gustavolira requested changes

2024-08-20 15:44 UTC, Omar-AlJaljuli commented on e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
> +  test('Test that roles and policies from GET request are what expected', async ({
Do I put these functions in the Common.ts file or in the rbac.spec.ts file?

2024-08-20 17:57 UTC, Omar-AlJaljuli commented on e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
> +test.describe.skip('Test RBAC plugin as an admin user', () => {
I forgot to remove the .skip while testing, don't merge yet.

2024-08-20 18:28 UTC, gustavolira commented on e2e-tests/playwright/e2e/plugins/rbac/rbac.spec.ts
> +    const expectedRoles =
can you move expectedRoles and expectedPolicies to a functional class?

2024-08-26 19:42 UTC, gustavolira commented
/test e2e-tests

2024-08-27 00:12 UTC, gustavolira approved these changes

2024-08-27 13:41 UTC, merged