chore(release): [1.2] verifying plugins have been released to npmjs.com and bumping versions
janus-idp/backstage-showcase pull request #1767
Opened 2024-10-14 14:55 UTC by Fortune-Ndlovu

## Description

[@janus-idp/backstage-plugin-jfrog-artifactory](https://www.npmjs.com/package/@janus-idp/backstage-plugin-jfrog-artifactory) The latest version on npm is 1.8.5

## Which issue(s) does this PR fix

- Fixes #? https://issues.redhat.com/browse/RHIDP-4217

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2024-10-14 16:30 UTC, Fortune-Ndlovu commented
cc: @nickboldt / @kim-tsao for review

2024-10-16 18:54 UTC, nickboldt requested changes
both 1.4.10 and 1.4.11 are 4 months old... why revert to the older one? 

https://www.npmjs.com/package/@janus-idp/backstage-plugin-jfrog-artifactory?activeTab=versions

I mean there's also 1.4.12 and 1.5.1... all the way up to 1.8.5.

2024-10-17 09:58 UTC, Fortune-Ndlovu commented
@nickboldt  I ended up bumping to [1.7.4](https://www.npmjs.com/package/@janus-idp/backstage-plugin-jfrog-artifactory/v/1.7.4), I think this bump is fine because main, and release-1.3 use 1.7.5

2024-10-17 10:39 UTC, Fortune-Ndlovu commented
/test images

2024-10-17 10:39 UTC, Fortune-Ndlovu commented
/test e2e-tests

2024-10-17 12:21 UTC, closed without merging

2024-10-21 09:01 UTC, Fortune-Ndlovu commented
closed because i have another PR open targeting all plugin versions https://github.com/janus-idp/backstage-showcase/pull/1795