chore(e2e): fix dynamic plugin names
janus-idp/backstage-showcase pull request #1869
Opened 2024-11-01 01:08 UTC by PatAKnight

## Description

There were recent updates to the names of dynamic plugins. This change may be what is causing issues with the failing e2e tests.

## Which issue(s) does this PR fix

- Fixes [RHIDP-4775](https://issues.redhat.com/browse/RHIDP-4775)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2024-11-01 12:05 UTC, PatAKnight commented
/test e2e-tests

2024-11-01 13:08 UTC, gashcrumb approved these changes

2024-11-01 14:58 UTC, gashcrumb approved these changes

2024-11-01 15:05 UTC, gustavolira commented
/test e2e-tests

2024-11-04 13:45 UTC, nickboldt approved these changes
looks reasonable to me

2024-11-04 14:35 UTC, schultzp2020 requested changes

2024-11-04 14:35 UTC, schultzp2020 commented on dynamic-plugins/wrappers/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic/src/dynamic/index.ts
> +import { createBackendFeatureLoader } from "@backstage/backend-plugin-api";
I don't see any related wrapper package.json changes.

2024-11-04 14:45 UTC, nilgaar commented
I see that we reached test execution, so that's and improvement (https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/janus-idp_backstage-showcase/1869/pull-ci-janus-idp-backstage-showcase-main-e2e-tests/1853429130473771008/artifacts/e2e-tests/janus-idp-backstage-showcase/build-log.txt).

But RHDH can't load the login view: https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/janus-idp_backstage-showcase/1869/pull-ci-janus-idp-backstage-showcase-main-e2e-tests/1853429130473771008/artifacts/e2e-tests/janus-idp-backstage-showcase/artifacts/showcase/index.html @PatAKnight any idea?

2024-11-06 00:09 UTC, PatAKnight commented
/retest

2024-11-06 11:36 UTC, PatAKnight commented
/retest

2024-11-06 17:42 UTC, gashcrumb commented on .ibm/pipelines/value_files/values_showcase.yaml
> +                  - authProvider: serviceAccount
Were these extra spaces actually needed?  There's a few changes in these files which seem more like a different tab width setting.  Not necessarily a big deal (except YAML) but does create extra unnecessary changes.

2024-11-06 18:00 UTC, merged

2024-11-06 18:13 UTC, josephca reviewed
/lgtm