chore(ci): add automated tests on GKE & fix AKS
janus-idp/backstage-showcase pull request #1918
Opened 2024-11-11 13:49 UTC by zdrapela

## Description

- Establish connection to GKE cluster using `gcloud` CLI.
- Add setup scripts for GKE deployments.
- Move AKS and GKE deployment functions out of the `openshift-ci-test.sh`.
- Replace AKS-specific namespace with K8S namespace/playwright project that both AKS and GKE can use.
- Change the creation of ConfigMaps.
- Fix AKS tests

The GKE nightly job will be established in this PR: https://github.com/openshift/release/pull/58943

## Which issue(s) does this PR fix

- Fixes [RHIDP-4552](https://issues.redhat.com/browse/RHIDP-4552), [RHIDP-4551](https://issues.redhat.com/browse/RHIDP-4551) and [RHIDP-4861](https://issues.redhat.com/browse/RHIDP-4861)

## PR acceptance criteria

✅ **AKS and GKE tests passed while running with a local `showcase-e2e-runner` built from `.ibm/images/Dockerfile`.**

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2024-11-19 06:34 UTC, zdrapela commented
/retest

2024-11-19 13:02 UTC, subhashkhileri commented
/retest

2024-11-19 14:18 UTC, subhashkhileri commented
/test e2e-tests

2024-11-20 08:07 UTC, subhashkhileri requested changes

2024-11-20 08:19 UTC, zdrapela commented on .ibm/pipelines/openshift-ci-tests.sh
> +  if [[ "$JOB_NAME" == *periodic* ]]; then
Good catch. I added a fix

2024-11-20 08:39 UTC, subhashkhileri commented
/lgtm

2024-11-20 09:29 UTC, zdrapela commented
/test e2e-tests

2024-11-20 11:05 UTC, zdrapela commented
/test e2e-tests

2024-11-20 11:15 UTC, zdrapela commented
/test e2e-tests

2024-11-20 14:45 UTC, subhashkhileri commented
/lgtm

2024-11-20 16:58 UTC, merged