style: reorder imports via prettier
janus-idp/backstage-showcase pull request #286
Opened 2023-06-01 19:15 UTC by schultzp2020

## Description

Please explain the changes you made here.

Reorders the imports to maintain parity with the janus plugins repo. https://github.com/janus-idp/backstage-plugins/pull/419

## Which issue(s) does this PR fix

N/A

## PR acceptance criteria

Please make sure that the following steps are complete:

- GitHub Actions are completed and successful
- Unit Tests are updated and passing
- E2E Tests are updated and passing
- Documentation is updated if necessary
- Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2023-06-01 19:56 UTC, PatAKnight commented on packages/app/src/App.tsx
> +    <Route path="/tech-radar" element={<TechRadarPage width={1500} height={800} id="default" />} />
So I see that a lot of these have been collapsed, I don't really have a preference either way but I wonder what other people think about the difference between the two? @christophe-f

2023-06-01 20:07 UTC, PatAKnight approved these changes
LGTM

2023-06-02 03:51 UTC, christophe-f requested changes
As discussed several times, we need to stay in parity with upstream. This PR will not be merged.

2023-06-02 13:58 UTC, schultzp2020 commented
> As discussed several times, we need to stay in parity with upstream. This PR will not be merged.

@christophe-f We have already merged a PR like this in https://github.com/janus-idp/backstage-plugins/pull/419. The only changes this PR is to the import order and does not diverge code logic wise from the upstream.

2023-06-15 14:34 UTC, closed without merging