feat(app): add dynatrace plugin
janus-idp/backstage-showcase pull request #307
Opened 2023-06-09 18:50 UTC by Zaperex

## Description

Adds the Dynatrace Plugin

## Which issue(s) does this PR fix

- Fixes #169 

## PR acceptance criteria

Please make sure that the following steps are complete:

- GitHub Actions are completed and successful
- Unit Tests are updated and passing
- E2E Tests are updated and passing
- Documentation is updated if necessary
- Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2023-06-12 14:15 UTC, schultzp2020 requested changes

2023-06-12 14:15 UTC, schultzp2020 commented on app-config.yaml
> +      apiKey: ${JENKINS_TOKEN}
```suggestion
  - name: default
    baseUrl: ${JENKINS_URL}
    username: ${JENKINS_USERNAME}
    apiKey: ${JENKINS_TOKEN}
```

Can you remove these changes and make a separate PR to fix this?

2023-06-15 21:39 UTC, schultzp2020 approved these changes
LGTM

2023-07-21 20:30 UTC, christophe-f approved these changes

2023-07-21 20:42 UTC, merged