feat: Read external data from s3
janus-idp/backstage-showcase pull request #312
Opened 2023-06-15 12:27 UTC by PatAKnight

## Description

Adds the AWS SDK to allow us to read in external data into the showcase app. The homepage and tech radar both have files store in an object bucket claim that we can use AWS to read from. There is also added logic that will default to the files stored in the source code so that the homepage and tech radar will still load data even without access to our OBC.

## Which issue(s) does this PR fix

- Fixes #79 

## PR acceptance criteria

Please make sure that the following steps are complete:

- GitHub Actions are completed and successful
- Unit Tests are updated and passing
- E2E Tests are updated and passing
- Documentation is updated if necessary
- Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2023-06-15 21:36 UTC, schultzp2020 requested changes
First pass

2023-06-15 21:36 UTC, schultzp2020 commented on packages/app/src/common.tsx
> +export const fetcher2 = async <T,>(urls: Parameters<typeof fetch>[]) => {
Delete `fetcher` and rename `fetcher2` to `fetcher`

2023-06-15 21:36 UTC, schultzp2020 commented on packages/app/src/components/home/HomePage.tsx
> +const useGetBaseURL = () => {
Should we extract this to a `helpers.ts` or `utils.ts` file?

2023-06-15 21:36 UTC, schultzp2020 commented on packages/app/src/lib/CustomTechRadar.ts
> +    ).then(async res => {
Use `await` to resolve promises.

2023-06-15 21:36 UTC, schultzp2020 commented on packages/backend/src/aws/router.ts
> +        (await transformedString?.then(data => data.toString())) || '',
Use `await` to resolve promises.

2023-07-11 13:06 UTC, PatAKnight commented
Going to close this as there is now a mechanism for reading in external data for the homepage and techradar

2023-07-11 13:06 UTC, closed without merging