draft: chore: update Dockefile for nodegyp...
janus-idp/backstage-showcase pull request #437
Opened 2023-08-18 15:40 UTC by nickboldt

### What does this PR do?

draft: chore: update Dockefile for nodegyp support downstream; remove all the needless named intermediate stages that don't work in OSBS

Signed-off-by: Nick Boldt <nboldt@redhat.com>

### Screenshot/screencast of this PR
N/A

### What issues does this PR fix or reference?
N/A (or see commit message above for issue number)

### How to test this PR?
N/A

### PR Checklist

[As the author of this Pull Request I made sure that:](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#pull-request-template-and-its-checklist)

- [x] [The Eclipse Contributor Agreement is valid](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-eclipse-contributor-agreement-is-valid)
- [x] [Code produced is complete](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-produced-is-complete)
- [x] [Code builds without errors](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#code-builds-without-errors)
- [ ] [Tests are covering the bugfix](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#tests-are-covering-the-bugfix)
- [x] [The repository devfile is up to date and works, if one exists](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#the-repository-devfile-is-up-to-date-and-works)
- [x] [Sections What issues does this PR fix or reference and How to test this PR completed](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#sections-what-issues-does-this-pr-fix-or-reference-and-how-to-test-this-pr-completed)
- [x] [Relevant user documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [Relevant contributing documentation updated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#relevant-contributing-documentation-updated)
- [x] [CI/CD changes implemented, documented and communicated](https://github.com/eclipse/che/blob/master/CONTRIBUTING.md#cicd-changes-implemented-documented-and-communicated)

### Reviewers

Reviewers, please comment how you tested the PR when approving it.

2023-08-21 19:48 UTC, schultzp2020 requested changes

2023-08-21 19:48 UTC, schultzp2020 commented on Dockerfile
> +# ENV EXTERNAL_SOURCE_NESTED=$REMOTE_SOURCES/upstream1/app/distgit/containers/rhdh-hub
```suggestion
# ENV EXTERNAL_SOURCE_NESTED=$EXTERNAL_SOURCE/distgit/containers/rhdh-hub
```

2023-08-21 19:49 UTC, schultzp2020 commented
@christophe-f should we create another Dockerfile for the downstream since they are diverging a decent bit.

2023-08-21 20:29 UTC, nickboldt commented on Dockerfile
> +# Downstream comment
if you prefer, I can just skip these unsupported intermediate stages with a sed command -- https://gitlab.cee.redhat.com/rhidp/cpaas-rhdh-hub/-/blob/rhdh-1.0-rhel-9/sync.sh#L242-243

2023-08-21 20:29 UTC, nickboldt commented on Dockerfile
> +# COPY $REMOTE_SOURCES/upstream1/cachito.env \
this whole block can be made smaller if upstream prefers the debugging stuff removed and streamlined.

2023-08-21 20:41 UTC, schultzp2020 commented
> if you prefer, I can just skip these unsupported intermediate stages with a sed command

> this whole block can be made smaller if upstream prefers the debugging stuff removed and streamlined.

@nickboldt both of these are probably a good idea. Ideally we should try to hide as much of the downstream as possible to make it easier to understand.

2023-08-22 14:13 UTC, nickboldt commented
> > if you prefer, I can just skip these unsupported intermediate stages with a sed command
> 
> > this whole block can be made smaller if upstream prefers the debugging stuff removed and streamlined.
> 
> @nickboldt both of these are probably a good idea. Ideally we should try to hide as much of the downstream as possible to make it easier to understand.

While I would prefer to say https://imgflip.com/i/7wjiiu?herp=1692707629737 I can rework this a bit to move some changes to the midstream.

HOWEVER this does mean the next time you change things in the Dockerfile, you'll have to check if you broke midstream.

Simpler might be to have TWO Dockerfiles... one for upstream and one called Dockerfile.rhel9 (?) so you can at least see the changes needed for both files in the same repo

2023-08-23 13:36 UTC, christophe-f commented
> @christophe-f should we create another Dockerfile for the downstream since they are diverging a decent bit.

Yes we could try that. We could have 2 files in the same repo, or one in midstream and downstream. We want to keep this simple and easy to maintain. We can also iterate on it and try different things.

2023-08-23 16:20 UTC, schultzp2020 approved these changes
LGTM

2023-08-23 17:44 UTC, merged