feat(backend): add Prometheus metrics
janus-idp/backstage-showcase pull request #469
Opened 2023-08-28 16:01 UTC by kadel

## Description

- Adds option (`METRICS_ENABLED=true`) to enable Prometheus metrics optionally.
- When enabled, Prometheus metrics are available at the backed URL in `/metrics ` (`http://localhost:7007/metrics`)

## Which issue(s) does this PR fix

- Fixes https://github.com/janus-idp/backstage-showcase/issues/230

## PR acceptance criteria

Please make sure that the following steps are complete:

- GitHub Actions are completed and successful
- Unit Tests are updated and passing
- E2E Tests are updated and passing
- Documentation is updated if necessary
- Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2023-08-28 17:17 UTC, schultzp2020 requested changes
First passthrough

2023-08-28 17:17 UTC, schultzp2020 commented on packages/backend/src/metrics.ts
> +// packages/backend/src/metrics.ts
remove

2023-09-05 21:33 UTC, schultzp2020 approved these changes
LGTM

2023-09-06 02:15 UTC, christophe-f approved these changes

2023-09-06 13:48 UTC, merged