feat: add AAP backend plugin
janus-idp/backstage-showcase pull request #511
Opened 2023-09-07 09:04 UTC by invincibleJai

## Description

Adds AAP (Ansible automation platform) backend plugin to the Showcase App.

## Which issue(s) does this PR fix

- Fixes https://github.com/janus-idp/backstage-showcase/issues/496

## Screenshots

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [x] Documentation is updated if necessary (requirement for new features)
- [x] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2023-09-07 14:50 UTC, Zaperex commented
I think you'll need to add a changeset for the backend package with `yarn changeset`

2023-09-08 17:54 UTC, christophe-f requested changes

2023-09-08 18:18 UTC, christophe-f commented
The plugin can be added to the list of plugins on the README

2023-09-08 18:28 UTC, Zaperex commented on app-config.yaml
> +        system: janus-idp
I believe the way the AAP backend plugin currently works is that it grabs job/workflow templates from AAP (so there's no `catalog-info.yaml` to refer to), which is why it's grabbing the information for the owner and system from the `app-config.yaml` to create the AAP catalog entities

2023-09-13 03:36 UTC, invincibleJai commented
> The plugin can be added to the list of plugins on the README

updated, @christophe-f PTAL when you get time.

2023-09-13 03:37 UTC, invincibleJai commented on app-config.yaml
> +        system: janus-idp
yeah, thanks @Zaperex for the comment.

2023-09-13 14:29 UTC, Zaperex commented on packages/backend/package.json
> +    "@janus-idp/backstage-plugin-aap-backend": "^1.2.2",
I think we should pin the dependency similar to how we're dealing with all the other dependencies

2023-09-13 14:45 UTC, Zaperex commented on packages/backend/src/plugins/catalog.ts
> +          frequency: { minutes: 1 },
All the other Entity Providers installed in the showcase currently use a frequency of 30 minutes or 1 hour, I think 1 minute might be a bit too frequent?

2023-09-14 03:36 UTC, christophe-f commented on app-config.yaml
> +        system: janus-idp
ok, then is it something we can remove?

2023-09-14 05:32 UTC, invincibleJai commented on app-config.yaml
> +        system: janus-idp
yeah, we can remove it as it's optional. If not provided it'll not show it and in OCM config we do pass owner https://github.com/janus-idp/backstage-showcase/blob/main/app-config.yaml#L224

2023-09-20 15:28 UTC, christophe-f commented on app-config.yaml
> +        system: janus-idp
yes it's good now. I guess we will have to remove this from the OCM plugin, but it's not related to this PR.

2023-09-20 15:30 UTC, christophe-f approved these changes
LGTM

2023-09-20 15:30 UTC, merged