chore: support `includes` in `dynamic-plugins.yaml`
janus-idp/backstage-showcase pull request #644
Opened 2023-10-23 12:55 UTC by davidfestal

## Description

Allow including files and overriding their content in the list of dynamic plugins 

## Which issue(s) does this PR fix

- Fixes #641

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2023-10-23 15:28 UTC, schultzp2020 requested changes
LGTM, https://github.com/janus-idp/backstage-showcase/pull/644#discussion_r1368701675

2023-10-23 16:50 UTC, davidfestal commented on showcase-docs/dynamic-plugins.md
> +- add the `@janus-idp/cli` dependency to use the `@janus-idp` fork of te backstage CLI that supports a new, required `export-dynamic-plugin` command,
Fixed

2023-10-23 16:50 UTC, davidfestal commented
> LGTM, [#644 (comment)](https://github.com/janus-idp/backstage-showcase/pull/644#discussion_r1368701675)

Fixed

2023-10-24 10:38 UTC, kadel approved these changes

2023-10-24 10:38 UTC, merged