feat(dynamic-plugins): add wrappers for frontend plugins
janus-idp/backstage-showcase pull request #683
Opened 2023-10-31 15:27 UTC by tumido

## Description

Add a dynamic plugin wrapper for frontend plugins we consume from upstream.

Similar to the backend plugins, with the only change that we do not need to additional code/interface, we just reexport the original plugin with additional metadata in `package.json`.

None of these plugins are consumed by the instance by default. This just creates all the necessary wrappers.

## Which issue(s) does this PR fix

N/A

## PR acceptance criteria

Please make sure that the following steps are complete:

- [x] GitHub Actions are completed and successful
- [x] Unit Tests are updated and passing
- [x] E2E Tests are updated and passing
- [x] Documentation is updated if necessary (requirement for new features)
- [x] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2023-11-02 09:34 UTC, davidfestal approved these changes

2023-11-02 14:36 UTC, tumido commented
Please hold. Will require rebase on top of https://github.com/janus-idp/backstage-plugins/pull/901

2023-11-03 04:26 UTC, schultzp2020 requested changes

2023-11-03 04:26 UTC, schultzp2020 commented on .gitignore
> +<<<<<<< HEAD
```suggestion
```

2023-11-03 04:26 UTC, schultzp2020 commented on .gitignore
> +>>>>>>> 8a67291 (feat(dynamic-plugins): add wrappers for frontend plugins)
```suggestion
```

2023-11-03 04:26 UTC, schultzp2020 commented on packages/app/package.json
> +    "@janus-idp/cli": "^1.3.2",
```suggestion
    "@janus-idp/cli": "1.3.2",
```

2023-11-03 14:09 UTC, schultzp2020 approved these changes
LGTM

2023-11-03 14:32 UTC, merged