Fix typo in the dynamic-plugins docs' package.json configurations
janus-idp/backstage-showcase pull request #702
Opened 2023-11-01 20:06 UTC by Zaperex

## Description

Fix typo in dynamic-plugins docs' `package.json` configurations
The current "recommended" `package.json` configuration will cause the `yarn install` and `yarn add` to fail due to `npm:janus-idp/backend-plugin-manager@0.0.5-janus.0` not being a valid package.

## Which issue(s) does this PR fix
N/A
## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2023-11-01 20:18 UTC, gorkem approved these changes

2023-11-02 08:52 UTC, davidfestal requested changes

2023-11-02 08:52 UTC, davidfestal commented on showcase-docs/dynamic-plugins.md
> +    "@backstage/backend-plugin-manager": "npm:@janus-idp/backend-plugin-manager@0.0.5-janus.0",
```suggestion
    "@backstage/backend-plugin-manager": "npm:@janus-idp/backend-plugin-manager@v1.19.6",
```
I believe that it is better to use the tag of the upstream backstage version here.

`@janus-idp/backend-plugin-manager` versions are tagged with the corresponding commit in the upstream backstage repository, and when built from an upstream release tag, with the corresponding backstage release tag.

2023-11-02 14:51 UTC, davidfestal approved these changes

2023-11-03 17:11 UTC, merged