chore(deps): Update aap, keycloak and ocm backends
janus-idp/backstage-showcase pull request #798
Opened 2023-11-20 16:01 UTC by jerolimov

## Description

Update dynamic-plugin peer dependencies to update AAP, Keycloak, and OCM backends to include this two PRs:

* https://github.com/janus-idp/backstage-plugins/pull/938
* https://github.com/janus-idp/backstage-plugins/pull/945

Fyi: The 2nd PR includes also a change in `@janus-idp/backstage-plugin-3scale-backend`, but this wasn't part of the peer dependencies yet.

## Which issue(s) does this PR fix

- Fixes #756 (and https://github.com/janus-idp/backstage-plugins/issues/629)

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2023-11-20 16:05 UTC, jerolimov commented
@Zaperex @kadel @schultzp2020 regarding https://github.com/janus-idp/backstage-showcase/issues/756#issuecomment-1806102755

Should I add 3scale similar to the other dynamic plugins? Is there anything else to do or to verify?

2023-11-20 16:46 UTC, Zaperex commented
3scale wasn't originally installed statically in the showcase, so I'm not sure if we should be including it dynamically as well. If we do want to include it, I think we'll want to include some default configurations in https://github.com/janus-idp/backstage-showcase/blob/main/dynamic-plugins.default.yaml and https://github.com/janus-idp/backstage-showcase/blob/main/app-config.dynamic-plugins.yaml.

2023-11-20 17:47 UTC, schultzp2020 approved these changes
LGTM

2023-11-20 18:19 UTC, davidfestal requested changes
I think @Zaperex remark [here](https://github.com/janus-idp/backstage-showcase/pull/798#issuecomment-1819439746) is right.

Could we split the PR, and keep the addition of the 3Scale plugin for a distinct PR ?

2023-11-20 20:07 UTC, tumido requested changes

2023-11-20 20:07 UTC, tumido commented on dynamic-plugins/imports/package.json
> +    "@janus-idp/backstage-plugin-3scale-backend": "1.3.4",
This plugin is missing configuration in `app-config.dynamic-plugins.yaml` and `dynamic-plugins.default.yaml`

2023-11-20 20:42 UTC, tumido commented
Also an important question - should 3scale even be included? Adding it into the base image we make it a supported plugin (no matter if disabled by default or not). Do we have a formal decision that 3scale is a supported plugin?

2023-11-20 22:30 UTC, jerolimov commented
Let me remove 3scale for now. :)

2023-11-20 22:33 UTC, tumido commented
As per https://redhat-internal.slack.com/archives/C05HGAR2DT5/p1700514326249259?thread_ts=1700250550.958579&cid=C05HGAR2DT5

3scale is not a supported plugin, therefore it should not be included in the image.

2023-11-20 22:53 UTC, jerolimov commented
I reverted this PR to my initial commit that just updates aap, keycloak and ocm backends.

2023-11-21 08:52 UTC, tumido approved these changes
/lgtm
/approve

2023-11-21 09:48 UTC, davidfestal approved these changes

2023-11-21 13:55 UTC, tumido approved these changes
/lgtm
/approve

2023-11-21 13:55 UTC, merged