WIP: Proof PR of switching the Showcase to the new backend system
janus-idp/backstage-showcase pull request #897
Opened 2024-01-23 12:33 UTC by davidfestal

## Description

This PR is a proof PR of what would be involved in switching the Showcase application to the new backend system.

It is not expected to be merged, but should instead besplit in several smaller PRs.

## Which issue(s) does this PR fix

This PR is related to EPIC https://github.com/janus-idp/backstage-showcase/issues/834

## PR acceptance criteria

Please make sure that the following steps are complete:

- [ ] GitHub Actions are completed and successful
- [ ] Unit Tests are updated and passing
- [ ] E2E Tests are updated and passing
- [ ] Documentation is updated if necessary (requirement for new features)
- [ ] Add a screenshot if the change is UX/UI related

## How to test changes / Special notes to the reviewer

2024-02-08 15:52 UTC, davidfestal commented
> Took a moment to give this a try locally and it seems to be working nicely with my basic config at least, nice!
> 
> I had a peek at the browser console and noticed these warnings, I think we need to be mindful of these as well, as this indicates a mismatch between what a plugin is expecting and what module is being provided by the application shell.
> 
> ![image](https://private-user-images.githubusercontent.com/351660/303393250-6fd84d9b-2fe2-4029-a258-12899582c86d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc0MDc0ODIsIm5iZiI6MTcwNzQwNzE4MiwicGF0aCI6Ii8zNTE2NjAvMzAzMzkzMjUwLTZmZDg0ZDliLTJmZTItNDAyOS1hMjU4LTEyODk5NTgyYzg2ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwOFQxNTQ2MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMzJhYzhlMTVhNzQwNTNjNGQ1MWRjNGJjNmI2ZTNlYzY3ZmYyNzRhMGEyODU5NGZhMzU4ZjBkMGI2ZDllMzMwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JU_3Kna9KCM-EsMC2ZL8SWp1NuQ28YDwBhh9KF_j8aE)
> 
> At the very least, if we do find some UI issues this would be the first warning to solve 😄

Thanks very much @gashcrumb for your testing.
I'll have a look at it.

2024-02-08 18:37 UTC, AndrienkoAleksandr commented
@davidfestal I test rbac-backend plugin for this pr using helm. I tested it with scaffolder, catalog and jenkins plugins - it works fine. But when I tried to enable rbac frontend plugin -  then init container failed. I used default rbac configuration: 

```
      - package: ./dynamic-plugins/dist/janus-idp-plugin-rbac
        disabled: false
        pluginConfig:
          dynamicPlugins:
            frontend:
              janus-idp.backstage-plugin-rbac:
                mountPoints:
                  - mountPoint: admin.page.rbac/cards
                    module: RbacPlugin
                    importName: RbacPage
                    config:
                      layout:
                        gridColumn: "1 / -1"
                        width: 100vw
                      props:
                        useHeader: false
                dynamicRoutes:
                  - path: /admin/rbac
                    module: RbacPlugin
                    importName: RbacPage
```

Event error: Back-off restarting failed container

2024-02-08 19:02 UTC, gashcrumb commented
>  - package: ./dynamic-plugins/dist/janus-idp-plugin-rbac

Should this be `janus-idp-backstage-plugin-rbac` instead?

2024-02-09 15:30 UTC, AndrienkoAleksandr commented
@gashcrumb, thanks you are right. rbac ui works too, but with fixed path.

2024-02-15 17:01 UTC, gashcrumb commented
@davidfestal created #972 about the version warning messages in the browser.

2024-02-15 20:03 UTC, schultzp2020 requested changes

2024-02-15 20:03 UTC, schultzp2020 commented on packages/backend/src/modules/rbacDynamicPluginsModule.ts
> +// theh the following commented code would be the right one.
```suggestion
// the the following commented code would be the right one.
```

Link to PR?

2024-02-15 20:36 UTC, davidfestal commented on packages/app/package.json
> +    "@backstage/app-defaults": "^1.5.0-next.3",
Fixed

2024-02-15 20:47 UTC, davidfestal commented on packages/backend/src/modules/rbacDynamicPluginsModule.ts
> +// theh the following commented code would be the right one.
Linked has been added

2024-02-15 20:49 UTC, schultzp2020 approved these changes
/approve
/lgtm

2024-02-15 21:30 UTC, merged